apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: java-app-servicemonitor
  namespace: prometheus        # Change this if your Prometheus is in a different namespace
  labels:
    release: stable            # CHANGED: Matches your other working 'stable-*' targets
spec:
  selector:
    matchLabels:
      app: java-app            # Must match the label on your Service
  endpoints:
  - port: web-metrics          # Must match the 'name' of the port in your Service
    path: /metrics
    interval: 15s
